### ISSUE TITLE
Unable to access individual videos and the videos endpoint

### ISSUE THREAD

**Issue by DakotahGodfrey** [art-institute-of-chicago/data-aggregator#31]
Trying to access the videos endpoint detailed in the docs [https://api.artic.edu/api/v1/videos](https://api.artic.edu/api/v1/videos) returns the following JSON:

![image](https://user-images.githubusercontent.com/78933339/122076195-ab897e00-cdc8-11eb-80e8-8e1b8bca81ce.png)

When attempting to access the videos/search endpoint [https://api.artic.edu/api/v1/videos/search](https://api.artic.edu/api/v1/videos/search) the following JSON is returned: 

![image](https://user-images.githubusercontent.com/78933339/122076637-0ae78e00-cdc9-11eb-8bd5-4326f581b3e1.png)

When attempting to access individual video resources by their identifier [https://api.artic.edu/api/v1/videos/1ee4a231-0dad-2638-24fd-dfa2138eb142](https://api.artic.edu/api/v1/videos/1ee4a231-0dad-2638-24fd-dfa2138eb142) a 404 is returned:

![image](https://user-images.githubusercontent.com/78933339/122077302-9cef9680-cdc9-11eb-8561-25eeb6fa932a.png)

**Comment by Mo7amedSMahdi** [comment]
Same here did you manage to find a solution?
