### ISSUE TITLE
`GET vs. POST` hash link in the docs points to a non-existent section

### ISSUE THREAD

**Issue by monocle** [art-institute-of-chicago/data-aggregator#63]
Was reading the API docs at https://api.artic.edu/docs/#get-vs-post and noticed the problem.
I'm happy to submit a PR to remove that warning if that's the way you'd like to go.

https://github.com/art-institute-of-chicago/data-aggregator/blob/9e00592425f211f721ae446a1f29dccc1a290bdb/docs/.sections/preface.md?plain=1#L82

Thanks for the API!

**Comment by nikhiltri** [comment]
Hey @monocle!

Thanks for the heads up! Looking back I don't see what this was meant to point to. I'll add some context to this dead link.

Thanks again!
nikhil
