### ISSUE TITLE
[Question] How can I retrieve the description from IIIF Manifests as a field?

### ISSUE THREAD

**Issue by CaioCerano** [art-institute-of-chicago/data-aggregator#64]
Hey, thanks for the amazing work!
I am using the artwork API. When I retrieve information using `/artworks/{id}/manifest.json` it returns a description, the same description that I can find when I look at a specific artwork page (e.g. www.artic.edu/artworks/16571).
I was wondering if there is a way to retrieve this description as a field or its ID using the `/artworks/{id}` endpoint (no manifest.json)

**Comment by nikhiltri** [comment]
Hey @CaioCerano!

My apologies for the slow response. We have been working on adding the description field back to our JSON endpoints for some time. We just pushed a release today that adds it back in! Note that that field is provided with a CC-By license, while all other fields in the `/artworks` endpoints are provided as CC0.

Thanks!
nikhil
